### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MareoRaft** [MareoRaft/tcr-analysis#1]
a running todo list...

  * log distance, params, accuracy to a file

**Comment by MareoRaft** [comment]
done.  next...

  * add an alternative `distance` function for comparison

**Comment by MareoRaft** [comment]
done. next...

  * add an alternative dist one-to-many function

**Comment by MareoRaft** [comment]
done. next...

- [x] make a function that loops through all combinations of hyperparams (inner dist func, outer dist func)
- [x] write function to combine counters together, so we can combine all person "A" things if we wish
- [ ] come up with a metric other than accuracy to measure which dist is best
- [x] run overnight w/ all 5 people to get some results

**Comment by MareoRaft** [comment]
Closing this now in favor of separate tickets.
